### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by mpetrunic**
Steps to add new translation:
- create a copy of `src/i18n/en_US.json` and name it accordingly
- in `src/index.js`:
   - add common locale data (available languages: `node_modules/intl/locale-data/jsonp')
   - add moment locale data (available: `node_modules/moment/locale`)
- write your translation strings in `src/i18n/xxx.json` file
- register you `src/i18n/xxx.json` file in `src/public_modules/I18n/sagas.js` under language key
- to change language either invoke changeLocale saga with your key or append `?lang=<language_key>`   and reload

### CODE REVIEW

**Comment by mbeylin** [comment]
@mpetrunic this looks great so far, I haven't noticed any issues.

Also-- great attention to detail (re-ordering import statements alphabetically) 🥇

**Comment by mbeylin** [comment]
@mpetrunic Great work on this bounty. I wanted to fix some of the merge conflicts I was noticing while reviewing the repo (since we have shipped some updates that include new icons and STDB2 since you began work on this.

I noticed that some files were not finished:
- /bounty/components/modals/IssueRatingFormModal/index.js
- /Leaderboard/Banner.js
- /Settings/index.js
- /Settings/sagas.js
- /explorer-components/BountyItem/index.js
- /hocs/RequireLoginComponent.js
- /layout/Header/index.js
- /layout/NoMatch/index.js
- /utils/constants.js
- /utils/validators.js

If you could go through and make the adjustments to those files, I would be happy to accept your submission (and re-merge your changes into the staging branch once more).

**Comment by mpetrunic** [comment]
@mbeylin Yeah sure!

**Comment by mbeylin** [comment]
@mpetrunic please let me know when you complete these updates so I can merge them in and accept your bounty submission.

**Comment by mpetrunic** [comment]
@mbeylin sorry, something came up, I will push updates tonight.

**Comment by mbeylin** [comment]
@mpetrunic No worries, I just wanted to check in :)

**Pull request merged**
