### PR TITLE
Increase z-index above the 15 z-index used for the modal

### PR DESCRIPTION
**Pull request by codeluggage**
Trello: https://trello.com/c/Cl8KYapC

@corwinharrell @villanuevawill Is this a silly way to fix this? I saw that the z-index of 15 was set for a reason in a PR 6 days ago, so figured setting the sidebar z-index above that made the most sense.

### CODE REVIEW

**Comment by codeluggage** [comment]
@villanuevawill which modals in particular? The ones I tried worked well - here's an example: 

screen shot 2018-10-11 at 23 34 39

**Comment by villanuevawill** [comment]
@codeluggage can you just try to increase the z-index on .navText?
https://github.com/Bounties-Network/Explorer/blob/master/src/components/Sidebar/Sidebar.module.scss

Does that work? Give that a shot real quick :) This solution scares me slightly.

**Comment by corwinharrell** [comment]
@villanuevawill what about this scares you exactly? As long as it doesn't have any negative downstream impact I don't see what's wrong with the change to the z-indexes. Altering the z-index of `.navText` would also likely work, just curious what the concern is around.

**Comment by codeluggage** [comment]
@villanuevawill that did not work, unless I'm doing it wrong. You can see the z-index for the `.navText` having been changed here:

screen shot 2018-10-16 at 00 36 22

**Comment by villanuevawill** [comment]
@codeluggage go for it

**Pull request merged**
