### PR TITLE
Debug broken form validation on the Bounties Explorer

### PR DESCRIPTION
**Pull request by Sm00g15**
This could also be done by adding an || in the if statement just below the added one if you'd like too.

### CODE REVIEW

**Comment by Sm00g15** [comment]
@mbeylin

**Comment by mbeylin** [comment]
@Sm00g15 this PR looks okay, but in my opinion doesn't address the root cause of the problem, which is that the `required` validation *should* be running for the deposit field, but isn't. Can you diagnose *that* problem?

**Comment by Sm00g15** [comment]
@mbeylin sure can, it’ll be because that field when empty has a value of NaN, so I’ll look into why that’s the case.

**Comment by mbeylin** [comment]
I suspect it might be due to the default values for the form, I think this issue only arose when we added bounty editing as a feature, which also uses the same container (with default values applied).

**Comment by Sm00g15** [comment]
@mbeylin finally got around to checking that and you were right, there was no default value set. I set that to 0 and removed the isNaN check and it should now work as expected.

**Comment by Sm00g15** [comment]
@mbeylin you were right, the issue was one level up in the initialValues section for the form. The default value of NaN was being passed through due to the type check of the of the string. I'm now passing through an empty value and the form is responding as it should.

**Comment by mbeylin** [comment]
Merged here: #383 

@Sm00g15 thank you for all of your help!

**Comment by Sm00g15** [comment]
@mbeylin glad that did the trick! You're totally welcome and Gitcoin is amazing! If you ever need any help feel free to holler! I'll be searching Gitcoin as well.

**Pull request merged**
