### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by mpetrunic**
@mbeylin missing translations

### CODE REVIEW

**Comment by mbeylin** [comment]
Looks good, except for the file `utils/constants.js` remains unchanged. Once that one is finished, this PR looks good and will be merged.

**Comment by mpetrunic** [comment]
@mbeylin That was left on purpose because I have to replace that with translation key but I can't figure out where is used. Webstorm is saying that it's never used :/

**Comment by mbeylin** [comment]
- the `DEFAULT_MARKDOWN` const is used in the MarkdownEditor component and in the CreateBounty container index.js
- the `notification_template` is used in /explorer-components/NotificationItem/index.js and in the public-modules/Notification/sagas.js file

**Comment by mpetrunic** [comment]
@mbeylin fixd

**Pull request merged**
