### PR TITLE
Translate the Bounties Explorer into Mandarin Chinese

### PR DESCRIPTION
**Pull request by ghost**
My work for this bounty. [https://explorer.bounties.network/bounty/3213](https://explorer.bounties.network/bounty/3213)
If there is any error or better translation, please comment below. :D thanks!

### CODE REVIEW

**Comment by ntkomata** [comment]
@mbeylin About line 865 in [en_US.json](https://github.com/Bounties-Network/Explorer/blob/master/src/i18n/en_US.json), the sentence 
```
What should bounty issuers submit as proof that they have completed the bounty?
```
, should it be 
```
What should bounty fulfillers submit as proof that they have completed the bounty?
```
?

**Comment by mbeylin** [comment]
Yes! You are absolutely correct, thank you for noticing this error.

**Comment by ntkomata** [comment]
NP :D

**Comment by ntkomata** [comment]
@mbeylin I just sent you an email and I feel like it may be flagged as spam

**Comment by ntkomata** [comment]
@mbeylin The bounty will expire soon, tho there arent really many comments. Will you pay me for the translation or how does this thing work?

**Pull request merged**
