### PR TITLE
Email interest signup

### PR DESCRIPTION
**Pull request by codeluggage**
Trello: https://trello.com/c/exXRchyB

Adds `email_interest` for the user settings. Corresponds to BountiesAPI PR: https://github.com/Bounties-Network/BountiesAPI/pull/193

### CODE REVIEW

**Comment by villanuevawill** [comment]
@corwinharrell do you want the preferences toggle here or another pattern?

**Comment by corwinharrell** [comment]
@codeluggage could you attach a screenshot?

**Comment by codeluggage** [comment]
Yeah @corwinharrell here's the current look: 
disabled
enabled

**Comment by corwinharrell** [comment]
Has there been any conversation about whether or not we plan to add to this list in the future? Is this just a one-off setting?

A couple thoughts. Since this is an email preference, I think it belongs with the other email preferences. The section label `Alerts` is a bit misleading since it is really just updates about the platform.

What do we think about the following:

1. Add this as a section immediately following `Email notifications`.
2. Change the section label to `Email Updates`
3. Change the section description text to read: `What other news would you like to receive via email?`

I think the toggle label can stay as-is

@villanuevawill @codeluggage

**Comment by codeluggage** [comment]
@corwinharrell I imagine this will have more detailed criteria in the future, like needing to match keywords/skills, needing payout to be over a certain amount, etc.

With the email notifications, but separately, is a much better place for it! 🙏  I actually got two of these modals mixed up. We have one for when you sign in for the first time with a new address and it opens the "ProfileDetails" modal. Then there's the regular settings when you click into your settings from the drop down. 

How about placing it prominently towards the top when you sign in for the first time and are adding profile details, so we can capture as many emails as possible here? Then place it below the other email notifications when you go click into your full settings later? 

And I suppose a follow up question - should we surface those email notification settings on that first "ProfileDetails" modal when you sign up, too? It's only showing this right now: 

screen shot 2018-09-20 at 14 36 37
screen shot 2018-09-20 at 14 36 10
screen shot 2018-09-20 at 14 28 51

**Comment by villanuevawill** [comment]
@codeluggage regarding adding the preferences to the signup modal - I think it would be overloading too much... but definitely a good point and something to think about for the future (it would probably be more work than it is worth).

@corwinharrell for now we will scrape this setting every month and add it to our marketing email list. That is what this is for.

@mbeylin I want to bring you into this discussion.  I think the original idea was to bring it to the top and make it more prominent... maybe having it as a checkbox makes it stand out differently... but regardless this works for me in general.

**Comment by corwinharrell** [comment]
I agree that adding all of the email preferences to the sign-up modal would be overwhelming. That being said, this had caused me to think about how we ask for email. Right now, the language that we use implies that the purpose of the email is to put on display for the community (less about receiving notifications and updates).

If we consider the user that wants to receive email notifications and updates, and therefore needs to provide their email, but does not want their email to be displayed say on the bounties that they create, do we need to think about decoupling this more?

@codeluggage the more I think about when this will be first introduced, the more I think following a more standard pattern is the way to go.

screen shot 2018-09-20 at 11 46 10 am

I'm not necessarily concerned about the placement of this element within this form, since they are required to scroll down to the end in order to submit. IMO it makes sense to ask them for this **after** they provide their email. This is often something seen as the last item before a form submission option, and I don't really see any reason to divert from that common practice. Thoughts?

@villanuevawill I'm also noticing that the implementation of the sign up instance of the account settings diverted from the original designs in that the footer says `Update profile` (how can you update something that hasn't been created before?) rather than `Submit details` and also has no option o `Cancel` which in the original designs allows the user to change their mind and return to the previous step of the sign up flow.

cc @mbeylin

**Comment by codeluggage** [comment]
@corwinharrell @villanuevawill 

I made the changes, and added a concept of "onboarding" to our UserSettings. That allows us to have slightly different copy and flow the first time someone is setting up their profile. Here's what that first modal looks like now: 

screen shot 2018-09-21 at 14 26 36

@corwinharrell your example had a light blue background, should I add that?

**Comment by corwinharrell** [comment]
@codeluggage In the first sign-up instance, I still feel like it's overkill to give this checkbox its own section with section label + description + input label. All of it together is quite redundant. Is there any objection to following the mockup more closely?

**Comment by codeluggage** [comment]
@corwinharrell No problem. The code is reused, which is why it gets its own section. I can just move the onboarding check higher up in the HTML tree and make the whole section different 👍

**Comment by corwinharrell** [comment]
@codeluggage awesome, and would you mind posting an example of how it appears on the profile settings page now?

**Comment by codeluggage** [comment]
@corwinharrell The `Checkbox` component we have isn't passed through the `FormInput` HOC and doesn't behave well in the form. It's not used anywhere else as far as I can see, so I'm changing it to be more like the `PreferencesToggle` so it can be used in the form.

**Comment by codeluggage** [comment]
@corwinharrell Alright here are the new updates 👍 I fixed the form issue and made it render without its section when the person is logging in for the first time. Not sure if there is a nice way we can add that blue you were showing in the mockup because that's not how the section box looks - maybe we can take a look at the CSS together if you want to tweak that or anything else about the styling. 

Here is the first login look now: 
screen shot 2018-09-23 at 16 49 09



And here is the settings page look now: 

screen shot 2018-09-23 at 16 33 31

**Comment by corwinharrell** [comment]
@codeluggage what happened to the email preferences in that account settings example?

**Comment by c-o-l-o-r** [comment]
@corwinharrell when a user logs in for the first time they don't see the email prefs in the initial modal, only the profile settings

**Comment by corwinharrell** [comment]
@c-o-l-o-r right that's understood. But in the screenshot above of the account settings page that @codeluggage posted the email preferences are absent. I'm curious if there's a better way to incorporate this with the email preferences.... I still feel like this lone checkbox having its own section with labels and description text is slightly excessive and the wording redundant.

**Comment by c-o-l-o-r** [comment]
@corwinharrell oh my bad you did say in the account settings example 😅

**Comment by codeluggage** [comment]
@corwinharrell Ah apologies, I misunderstood - the email preferences are handled and stored differently. I understood that it would look different between onboarding and account settings, i.e. the section title and description.

The email preferences are saved with a different button, and are not part of the onboarding. If we make this checkbox part of the email preferences, it would have to save together with them too (the `Save Email Preferences` button at the bottom). That means it wouldn't be possible to save it using the same button when onboarding, because that re-uses the account settings. 

We could show the entire thing both places, and merge both save buttons into one? That way it would work both places and you get all the choices when you initially sign up. This is what @villanuevawill was hesitant to earlier in this thread though. 

Happy to make any changes we want to here, but to avoid messy code, we need to either merge them completely, or keep them separate, in my opinion.

**Pull request merged**
